apiVersion: v1
kind: Service
metadata:
  name: kafka-server
spec:
  type: NodePort
  selector: 
    app: kafka-server
  ports:
  - name: kafka-broker
    port: 9092
    targetPort: 9092
    nodePort: 30036
    protocol: TCP