apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafka-zookeeper
  template:
    metadata:
      labels:
        run: kafka-zookeeper
    spec:
      containers:
        - name: kafka-zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"